### ISSUE TITLE
Is this package deprecated?

### ISSUE THREAD

**Issue by xavi-developer** [tumblr/tumblr.php#115]
Hello,
I have noticed some recent updates for documentation and testing, but it's been 4 years since the [last release v0.4.0](https://packagist.org/packages/tumblr/tumblr#v0.4.0). I am trying to use it with [guzzle v7](https://packagist.org/packages/guzzlehttp/guzzle#7.0.0) (one year since it was released) but composer specifies to use guzzle 6. 

Would there be any chance to update it to work with guzzle 7?

Thanks.

**Comment by westy92** [comment]
Here's a PR to update guzzle: https://github.com/tumblr/tumblr.php/pull/116

**Comment by xavi-developer** [comment]
> Here's a PR to update guzzle: #116

Great, thank you very much!

**Comment by westy92** [comment]
I just switched to using guzzle directly:

```json
"guzzlehttp/guzzle": "^7.0",
"guzzlehttp/oauth-subscriber": "^0.5",
```

since they aren't abandoned like it appears this package is.

Usage:

```php
$tumblrStack = \GuzzleHttp\HandlerStack::create();
$tumblrMiddleware = new \GuzzleHttp\Subscriber\Oauth\Oauth1([
  'consumer_key'    => '',
  'consumer_secret' => '',
  'token'           => '',
  'token_secret'    => '',
]);
$tumblrStack->push($tumblrMiddleware);
$tumblrClient = new \GuzzleHttp\Client([
  'base_uri' => 'https://api.tumblr.com/v2/',
  'handler' => $tumblrStack,
  'auth' => 'oauth',
]);

$response = $tumblrClient->post('blog/myblog.tumblr.com/post', [
  'form_params' => [
    'type' => 'link',
    // ...
  ],
]);

echo 'Responded with ' . $response->getStatusCode() . ': ' . $response->getBody() . PHP_EOL;
```

**Comment by fredmeng** [comment]
Hi there, is anyone going to update the package on Packagist as well?  https://packagist.org/packages/tumblr/tumblr#dev-master

**Comment by sanmai** [comment]
That’s the plan, yes. I’d like to do a bit more testing before this happens.

**Comment by sanmai** [comment]
It's live! Please report any issues.
