### ISSUE TITLE
 Uncaught Tumblr\API\RequestException: [401]: Not Authorized thrown

### ISSUE THREAD

**Issue by GoncaloMiguel** [tumblr/tumblr.php#22]
Hi, i´m using oauth  as found in https://github.com/tumblr/tumblr.php/wiki/Authentication 

But i´m getting 

"Fatal error: Uncaught Tumblr\API\RequestException: [401]: Not Authorized thrown in ../tumblr/lib/Tumblr/API/Client.php on line 427"
can you help me ? 

Thanks in advance, 
Gonçalo

``` php
require_once('vendor/autoload.php');

// some variables that will be pretttty useful
$consumerKey = 'XXX';
$consumerSecret = 'YYY';

// some variables that will be pretttty useful
$client = new Tumblr\API\Client($consumerKey, $consumerSecret);
$requestHandler = $client->getRequestHandler();
$requestHandler->setBaseUrl('https://www.tumblr.com/');

//IF Receive oauth
if(!$_GET['oauth_verifier']){
    // start the old gal up
    $resp = $requestHandler->request('POST', 'oauth/request_token', array());

    // get the oauth_token
    $out = $result = $resp->body;
    $data = array();
    parse_str($out, $data);

    // tell the user where to go
    echo '<a href="https://www.tumblr.com/oauth/authorize?oauth_token=' . $data['oauth_token'].'"> GO </a>';
    $client->setToken($data['oauth_token'], $data['oauth_token_secret']);
    $_SESSION['t']=$data['oauth_token'];
    $_SESSION['s']=$data['oauth_token_secret'];
} else {//IF i don´t Receive oauth

    // get the verifier (will be in URL that the user comes back to)
    echo "\noauth_verifier: ";
    $handle = fopen('php://stdin', 'r');
    $line = fgets($handle);

    // exchange the verifier for the keys
    $verifier = trim($line);

    $verifier = $_GET['oauth_verifier'];

    $token = $_SESSION['t'];
    $secret = $_SESSION['s'];

    //FROM tumblrPHP    
    $resp = $requestHandler->request('POST', 'oauth/access_token', array('oauth_verifier' => $verifier));

    $out = $result = $resp->body;
    $data = array();
    parse_str($out, $data);

    // and print out our new keys
    $token = $_SESSION['t'];
    $secret = $_SESSION['s'];
    echo "\ntoken: " . $token . "\nsecret: " . $secret;

    // and prove we're in the money
    $client = new Tumblr\API\Client($consumerKey, $consumerSecret, $token, $secret);
    $info = $client->getUserInfo();
    echo "\ncongrats " . $info->user->name . "!\n";

    }
```

**Comment by clozeQH** [comment]
Undefined index: oauth_token
Undefined index: oauth_token_secret

these are the errors that i got after executing the code..anyone has any idea?

**Comment by mrniamster** [comment]
> ```
> $client = new Tumblr\API\Client($consumerKey, $consumerSecret);
> $requestHandler = $client->getRequestHandler();
> $requestHandler->setBaseUrl('https://www.tumblr.com/');
> 
> // If we are visiting the first time
> if (!$_GET['oauth_verifier']) {
> 
>     // grab the oauth token
>     $resp = $requestHandler->request('POST', 'oauth/request_token', array());
>     $out = $result = $resp->body;
>     $data = array();
>     parse_str($out, $data);
> 
>     // tell the user where to go
>     echo '<a href="https://www.tumblr.com/oauth/authorize?oauth_token=' . $data['oauth_token'].'"> GO </a>';
>     $_SESSION['t']=$data['oauth_token'];
>     $_SESSION['s']=$data['oauth_token_secret'];
> 
> } else {
> 
>     $verifier = $_GET['oauth_verifier'];
> 
>     // use the stored tokens
>     $client->setToken($_SESSION['t'], $_SESSION['s']);
> 
>     // to grab the access tokens
>     $resp = $requestHandler->request('POST', 'oauth/access_token', array('oauth_verifier' => $verifier));
>     $out = $result = $resp->body;
>     $data = array();
>     parse_str($out, $data);
> 
>     // and print out our new keys we got back
>     $token = $data['oauth_token'];
>     $secret = $data['oauth_token_secret'];
>     echo "token: " . $token . "<br/>secret: " . $secret;
> 
>     // and prove we're in the money
>     $client = new Tumblr\API\Client($consumerKey, $consumerSecret, $token, $secret);
>     $info = $client->getUserInfo();
>     echo "<br/><br/>congrats " . $info->user->name . "!";
> 
> }
> ```

Thanks you so much
