### ISSUE TITLE
I keep getting this error Fatal error: Class 'Eher\OAuth\HmacSha1' not found in

### ISSUE THREAD

**Issue by mase857** [tumblr/tumblr.php#23]
I get this error  Fatal error: Class 'Eher\OAuth\HmacSha1' not found in,  I tried to install Eher folder data on windows , but for some reason I have an issue with  the php_imagick.dll when I run the command curl -sS https://getcomposer.org/installer | php
php composer.phar install --no-dev

Is there any way I can install both the Eher and Tumblr PHP files alltogether manually ? and can you explain me the hierarchy of the Tumblr Folder and the Eher , because I installed the Tumblr Foler in my FTP (Tumblr/API/Client.php,RequestException.php,RequestHandler.php) and then I installed the Eher folder in the API folder .. which i thought would work , but it's still giving me those errors ... Any help regarding this issue would be greatly appreciated.... If there's a way I can install both the Tumblr and Eher folders alltogether to avoid these path errors , that'd be great.

**Comment by earth-tone** [comment]
I don't see an Eher class anywhere in this project? I have the same error.
