### ISSUE TITLE
reblogPost method

### ISSUE THREAD

**Issue by Colir** [tumblr/tumblr.php#39]
Hi,
i want to know how to change the original caption of a post when reblogging it.
With the API, the original caption are still present when reblogging, however when reblogging on tumblr, we can change it in the editor...
How to archive this ?
thanks

**Comment by Colir** [comment]
please ?

**Comment by khurshid-alam** [comment]
First get the ```post_id``` and ```type``` of your new re-blogged post. Then use ```api.tumblr.com/v2/blog/{base-hostname}/post/edit``` and pass ```post_id``` along with required parameter like ```caption``` (for photo post), ```title, body``` (for text posts) according to the type of the post.

**Comment by Colir** [comment]
i 'll try. i came back soon. thanks

**Comment by ceykooo** [comment]
This no longer works by design. See here for details: http://support.tumblr.com/post/128127169452/ever-see-a-crazy-long-indecipherable-reblog-chain
