### ISSUE TITLE
Bool to string conversion fix not merged

### ISSUE THREAD

**Issue by fauxpark** [tumblr/tumblr.php#42]
Since I didn't get a reply to my comment on #27... :P Somehow d79576f didn't get put in master. Interestingly seejohnrun/tumblr.php@d79576f looks perfectly fine. I'm guessing some weird stuff related to moving the repo over to the tumblr org.

**Comment by ceykooo** [comment]
@fauxpark This should now be resolved on the backend, so the fix is no longer necessary.

``` php
$reblog_info = 'true';
$posts = $client->getBlogPosts('staff.tumblr.com', array('reblog_info' => $reblog_info));
$reblog_info_posts = array_filter($posts->posts, function($p) { return isset($p->reblogged_from_id); });
if ($reblog_info_posts) {
    echo "It worked!\n";
} else {
    echo "No reblogs :(\n";
}
```

Which gives an output of:

```
It worked!
```

Testing with `false`, `'false'`, `true`, `1` and `0` also give the expected results.
