### ISSUE TITLE
fine on localhost, but error on AWS: "Fatal error: Class 'Tumblr\API\Client' not found"

### ISSUE THREAD

**Issue by pdme** [tumblr/tumblr.php#49]
I have used composer to install (see below), which works fine on my localhost. But after deploying it on an Amazon Web Services PHP server, it throws the error: "Fatal error: Class 'Tumblr\API\Client' not found".

Any thoughts?

Thanks!

    {
        "require": {
            "tumblr/tumblr": "dev-master"
        }
    }

**Comment by khurshid-alam** [comment]
See answer to this issue: https://github.com/tumblr/tumblr.php/issues/45

**Comment by pdme** [comment]
thanks!

**Comment by pdme** [comment]
Thanks for your reply, but I'm afraid it hasn't solved my problem.

I uploaded through git / eb (the elastic beanstalk cli), and vendor is not included in .gitignore.

It may have something to do with the structure of my app, which uses multiple social media channels, and loads a different autoload.php depending on the user's request (Tumblr, Facebook, etc.):

    app
        /lib
            /streams
                /facebook
                    composer.json
                    vendor
                    etc
                /tumblr
                    composer.json
                    vendor
                    etc

All other libraries are loaded in the same way - Facebook, Instagram, Twitter - and load fine.

Thanks again!

**Comment by Pierreparis** [comment]
Hi ,

I have the same problem although I installed my tumblr app and all, that don't work and show me this:

Fatal error: Class 'Tumblr\API\Client' not found

**Comment by pdme** [comment]
No, it's not the same for me. I installed the tumblr library with composer, which gives you the /vendor dir. You then only have to include the autoload.php within that dir to start using the library (https://getcomposer.org/).

**Comment by khurshid-alam** [comment]
@pdme You must provide appropriate path (relative on AWS). For example, if your source code file is in `app` directory then you can load the library using
```php
<?php
require 'lib/streams/tumblr/vendor/autoload.php';
?>
```
Change the path relative to the `app` folder on the AWS. Relative path on AWS could be very different than the local machine.

**Comment by khurshid-alam** [comment]
@Pierreparis If a library has dependencies then you have to load all those dependencies as well(each from different folder). That is why `composer` method is recommended.

For example, this tumblr library depends on `ether` & `guzzle`. So you have to install & load those as well.

**Comment by pdme** [comment]
@khurshid-alam autoload.php is found, otherwise require_once would have thrown an error.

Instead, it's creating an instance of the Tumblr API that throws an error in the line after:

    require_once('vendor/autoload.php');
    $client = new Tumblr\API\Client(xxxx);

**Comment by khurshid-alam** [comment]
@pdme That's weird. 

What does autoload.php contain on AWS? You can check this by logging via ssh & running `cat autload.php`.

Also make sure files actually exist inside vendor directory on AWS. `eb` has a old bad habit to compress/ignore whenever it finds the word `vendor` during git push. In any case, remove & then re-install.

Finally try:
```php
require_once('lib/streams/tumblr/vendor/autoload.php');
$consumerKey = "xxxx.....";
$consumerSecret = "xxxx... "; 
$token = "xxx......";
$secret = "xxx.....";
$client = new Tumblr\API\Client($consumerKey, $consumerSecret, $token, $secret);
```

**Comment by Pierreparis** [comment]
OK I'll try to install it with the composer and then tell you if it work thanks!

**Comment by pdme** [comment]
@khurshid-alam I figured it out: The problem is the tumblr API gets installed as a git submodule, and AWS doesn't support submodules.

The solution is to deinit the tumblr API as a submodule, and then push.
