### ISSUE TITLE
Multiple file upload not working

### ISSUE THREAD

**Issue by zoster81** [tumblr/tumblr.php#50]
Sorry for my bad english..
I can post a single image, but error whit 2 or more image

My code for one image, working code 

$data = array(
  "type"=> "photo",
  "caption"=>"caption test",
  "tags"=>"test,prova",
  "link"=>"www.google.it",
  "data"=>"./nutriA.png");

  $client->createPost($blog->name, $data);

code for multiple image, not working code

$path   = "./nutriA.png";
$pathb = "./nutriB.png";

$data = array(
  "type"=> "photo",
  "caption"=>"retest",
  "tags"=>"test,prova",
  "link"=>"www.google.it",
  "data"=>array($path, $pathb));

$client->createPost($blog->name, $data);

output of var_dump($data);

array(5) {
  ["type"]=>
  string(5) "photo"
  ["caption"]=>
  string(6) "retest"
  ["tags"]=>
  string(10) "test,prova"
  ["link"]=>
  string(13) "www.google.it"
  ["data"]=>
  array(2) {
    [0]=>
    string(12) "./nutriA.png"
    [1]=>
    string(12) "./nutriB.png"
  }
}

error log :
[03-Feb-2015 15:55:43 Europe/Rome] PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\RequestException' with message 'File must be a string or instance of PostFileInterface' in /home2/panperfo/public_html/rss/tumblr/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php:226
Stack trace:
#0 /home2/panperfo/public_html/rss/tumblr/vendor/tumblr/tumblr/lib/Tumblr/API/RequestHandler.php(108): Guzzle\Http\Message\EntityEnclosingRequest->addPostFiles(Array)
#1 /home2/panperfo/public_html/rss/tumblr/vendor/tumblr/tumblr/lib/Tumblr/API/Client.php(468): Tumblr\API\RequestHandler->request('POST', 'v2/blog/vetrina...', Array)
#2 /home2/panperfo/public_html/rss/tumblr/vendor/tumblr/tumblr/lib/Tumblr/API/Client.php(407): Tumblr\API\Client->makeRequest('POST', 'v2/blog/vetrina...', Array, false)
#3 /home2/panperfo/public_html/rss/tumblr/vendor/tumblr/tumblr/lib/Tumblr/API/Client.php(228): Tumblr\API\Client->postRequest('v2/blog/vetrina...', Array, false)
#4 /home2/panperfo/public_html/rss/tumblr/tumblr.php(57): Tumblr\API\Client->createPost('vetrinav in /home2/panperfo/public_html/rss/tumblr/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php on line 226

guzle version 3.9.2 (2014-09-10)
i've tryed various mode od doing the image array, also tryed using source(i know wrong way), always get error

**Comment by zoster81** [comment]
sorry, i was not using the last version, i was using the version supplied by composer, but how i can use composer to install the latest current version?

**Comment by khurshid-alam** [comment]
Use :

```
{
  "require" : {
    "tumblr/tumblr": "dev-master"
  }
}
```

**Comment by zoster81** [comment]
thank for your answer :D but where i have to put this code? i'm new to composer

**Comment by khurshid-alam** [comment]
inside `composer.json` file. Then run `php composer.phar install`. Learn more about Composer at  https://getcomposer.org/doc/03-cli.md
