### ISSUE TITLE
how to format data for photosets?

### ISSUE THREAD

**Issue by benoitwimart** [tumblr/tumblr.php#51]
Hi,

I can post a photo with `$client->createPost($blogName, $data);`
```php
$data = array();
$data['type'] = "photo";
$data['tags'] = "foo, bar";
$data['source'] = "/path/to/mypicture.jpg";
```
but how to do this with a photosets ?

**Comment by benoitwimart** [comment]
I found the solution, use relative path to image (external path/domain works with photo post not photoset)…

**Comment by khurshid-alam** [comment]
May be something like:

```php
$data['source'] = array("/path/to/imag1.jpg", "/path/to/image2.jpg");
```
