### ISSUE TITLE
Updating to Guzzle 5 >

### ISSUE THREAD

**Issue by tim-hanssen** [tumblr/tumblr.php#53]
It would be great if the plugin requirements could meet a newer version for Guzzle.
We're getting so many conflicts because other SDKs require a newer version.

**Comment by khurshid-alam** [comment]
@tim-hanssen 

In composer.json
```json
  "require": {
    "eher/oauth": "1.0.*",
    "guzzle/guzzle": ">=3.1.0,<4"
  }
```

You can remove `<4` to see if it is working. It is there probably for compatibility issue with php `<=5.3.3`

**Comment by jcorry** [comment]
the newer versions of Guzzle have a different response handling and a different way of configuring requests that is incompatible. This should definitely be upgraded to current Guzzle version...

**Comment by matheusmariano** [comment]
I have a Tumblr PHP project on GitHub that uses the newer version of Guzzle. Feel free to suggest or contribute with new methods or features.
https://github.com/matheusmariano/tumblr-php
