### ISSUE TITLE
Edit post comment

### ISSUE THREAD

**Issue by Colir** [tumblr/tumblr.php#54]
Hi.
I'm trying to edit a post by changing the comment. But this doesn't work...
I can succesfully change the tags, or add comments when i reblog or edit a post.
But can edit comment on an edit action.

Is this possible to edit the comment of a particular post ?

thanks

**Comment by ceykooo** [comment]
You might want to make sure you're changing the correct "comment" field for the post type. For example, it is `body` in a text post, but `caption` in a photo post. Here's a example for a text post:

``` php
$res = $client->editPost('ceyko-dev.tumblr.com', 125263497466, array('body' => 'I edited this.'));
```

Also, note that you can only edit your own comments. You cannot change other people's comments.
