### ISSUE TITLE
OAuth with v2/tagged doesn't work

### ISSUE THREAD

**Issue by hagent92** [tumblr/tumblr.php#57]
According to the API docs v2/tagged can be requested with api_key or OAuth. However ... when I try OAuth I always get a "401 Not Authorized" (posting, etc. works).

**Comment by matheusmariano** [comment]
Can you show me the code?

**Comment by ceykooo** [comment]
OAuth does indeed work correctly on the tagged route. We can validate that it is working correctly via the presence of the `liked` property on a post, which only shows up for logged-in requests:

``` php
$client = new Tumblr\API\Client('...','...');

echo 'Requesting without OAuth. Has `liked` field? ';
$posts = $client->getTaggedPosts('gif');
echo (isset($posts[0]->liked) ? 'yes' : 'no') . "\n";

$client->setToken('...','...');
echo 'Requesting with OAuth. Has `liked` field? ';
$posts = $client->getTaggedPosts('gif');
echo (isset($posts[0]->liked) ? 'yes' : 'no') . "\n";
```

Which produces an output of:

```
Requesting without OAuth. Has `liked` field? no
Requesting with OAuth. Has `liked` field? yes
```
