### ISSUE TITLE
Like success but  return an empty array

### ISSUE THREAD

**Issue by semau** [tumblr/tumblr.php#59]
Hi,
I try to:
    echo  json_encode($this->client->like($_POST["id"], $_POST["reblogKey"]));
it's success (I checked my account in tumblr) but in return I get `[]`
How I can be sure that the "Like" indeed manage?
Best,
MIchael

**Comment by ceykooo** [comment]
@semau If the request fails, an exception will be thrown: `Tumblr\API\RequestException`.

The `statusCode` and `message` of the exception will differ based on how it fails. For example, a 404 indicates that a post with the given reblog key could not be found. While a 401 indicates that your tokens are invalid.

If you don't receive an exception, the request was successful. Liking a post just happens to return an empty response on success, hence the `[]`.
