### ISSUE TITLE
Add tags to reblog

### ISSUE THREAD

**Issue by semau** [tumblr/tumblr.php#60]
Hi,
I reblog a post like that:

    $this->client->reblogPost($userBlogInfo->name, $post_id, $_POST["reblogKey"], $options = null)

How can I add tags to reblog?
Regards,
Michael

**Comment by matheusmariano** [comment]
Reading the [API Docs#rebloging](https://www.tumblr.com/docs/en/api/v2#reblogging), I think isn't possible to reblog with tags.

**Comment by matheusmariano** [comment]
Have you tried to use `['tags' => 'your, list, of, tags']` in the options parameter?
Source: [API Docs: Posting](https://www.tumblr.com/docs/en/api/v2#posting)

**Comment by semau** [comment]
Oh, I thought I can use only in: https://www.tumblr.com/docs/en/api/v2#reblogging
Thanks
