### ISSUE TITLE
Authentication: cURL error

### ISSUE THREAD

**Issue by triplike1do** [tumblr/tumblr.php#63]
I'm using https://github.com/tumblr/tumblr.php/wiki/Authentication as an example, but when I try to verify auth, by sending POST request to `oauth/access_token` I get only curl error: `[curl] 56: SSLRead() return error -9806 [url] https://www.tumblr.com/oauth/access_token`

**Comment by triplike1do** [comment]
it only happens on my localhost, with PHP-builtin server. When I uploaded the project to server, it worked as it should be. What can be a problem on localhost?

**Comment by matheusmariano** [comment]
Do you use OS X Yosemite or El Capitan? I had a similar problem with SSL, I don't know why. I recommend to develop PHP projects using [Vagrant Homestead](http://laravel.com/docs/5.1/homestead). It's very practical.

**Comment by triplike1do** [comment]
yes, I use El Capitan. But I work with cURL every day, and so far the only problem is with this SDK. But okay, it's not critical anymore
