### ISSUE TITLE
Link to app in post

### ISSUE THREAD

**Issue by alexlavr** [tumblr/tumblr.php#64]
When I use [Yahoo Tumblr iOS SDK](https://developer.yahoo.com/flurry/docs/tumblrsharing/) to share, my post on Tumblr displays a link to the app:

<img src="https://cloud.githubusercontent.com/assets/213710/12706660/83e2888c-c857-11e5-90e6-bd070ac04d13.PNG" width="360" />

Is there a way to do this with the PHP SDK?

**Comment by matheusmariano** [comment]
I'm not sure if there is a way to do that with PHP SDK.

**Comment by ceyko** [comment]
This is not something that is controlled via the API/SDK. Please contact Tumblr Support for more info about this: tumblr.com/support
