### ISSUE TITLE
Make getRequest a public method

### ISSUE THREAD

**Issue by javalight** [tumblr/tumblr.php#67]
There are endpoints that this api does not cover, i would like to call the endpoints my self but the getRequest and postRequest methods are private.

**Comment by matheusmariano** [comment]
It's true. Unfortunately this repository isn't maintained for a long time and probably you will not get a solution now. I recommend you to use the package I created to solve problems like these.

https://github.com/matheusmariano/tumblr-php

Feel free to ask or suggest anything. 😄

**Comment by javalight** [comment]
Thanks for the tip, ill look into it if i have any problems but in the mean time i used the getRequestHandler method to handle it

$client->getRequestHandler()->request($method,$endPoint,$params);

Actually this is probably how they intended there api to be used... lol
