### ISSUE TITLE
PHP Fatal error:  Uncaught Tumblr\\API\\RequestException: [401]: Unauthorized\n\n

### ISSUE THREAD

**Issue by andrewbecks** [tumblr/tumblr.php#72]
Hi. I'm getting an error message that is similar to what was discussed in issue #22, but I'm not able to resolve it and would appreciate any help/feedback as to what I'm doing wrong. Starting with some of the example code in #22, I'm able to retrieve the blog information fine (ex: `$info->user->name`), but post creation seems to fail, with the following apache error.log messages:

```
[Wed Sep 21 12:28:37.327302 2016] [:error] [pid 16206] [client 50.132.230.189:60340] PHP Fatal error:  Uncaught Tumblr\\API\\RequestException: [401]: Unauthorized\n\n  thrown in /var/www/html/tumblrAPI/vendor/tumblr/tumblr/lib/Tumblr/API/Client.php on line 427
```

Here's the full code. I've redacted the consumer key, consumer secret, and blogName, but everything else is in tact.

```
<?php
session_start();

require_once('vendor/autoload.php');

$consumerKey = 'PLACE HERE';
$consumerSecret = 'PLACE HERE';
$blogName = 'PLACE HERE'; // blogname.tumblr.com

$client = new Tumblr\API\Client($consumerKey, $consumerSecret);
$requestHandler = $client->getRequestHandler();
$requestHandler->setBaseUrl('https://www.tumblr.com/');

// If we are visiting the first time
if (!$_GET['oauth_verifier']) {

    // grab the oauth token
    $resp = $requestHandler->request('POST', 'oauth/request_token', array());
    $out = $result = $resp->body;
    $data = array();
    parse_str($out, $data);

    // tell the user where to go
    echo '<a href="https://www.tumblr.com/oauth/authorize?oauth_token=' . $data['oauth_token'].'"> GO </a>';
    $_SESSION['t']=$data['oauth_token'];
    $_SESSION['s']=$data['oauth_token_secret'];

} else {

    $verifier = $_GET['oauth_verifier'];

    // use the stored tokens
    $client->setToken($_SESSION['t'], $_SESSION['s']);

    // to grab the access tokens
    $resp = $requestHandler->request('POST', 'oauth/access_token', array('oauth_verifier' => $verifier));
    $out = $result = $resp->body;
    $data = array();
    parse_str($out, $data);

    // and print out our new keys we got back
    $token = $data['oauth_token'];
    $secret = $data['oauth_token_secret'];
    echo "token: " . $token . "<br/>secret: " . $secret;

    $client = new Tumblr\API\Client($consumerKey, $consumerSecret, $token, $secret);
    $info = $client->getUserInfo($blogName);

    echo "<br/><br/>congrats " . $info->user->name . "!";    

    $client3 = new Tumblr\API\Client($consumerKey, $consumerSecret, $token, $secret);
    $data = array(
        'type' => 'link',
        'title' => 'title',
        'url' => 'http://www.yahoo.com',
        'description' => 'my sample tumblr post',
        'publisher' => 'me',
        'photos' => array(
            'width' => '1920',
            'height' => '1080',
            'url' => 'https://i.ytimg.com/vi/m5d1FlSeF-M/maxresdefault.jpg'
        )
    );

    $post = $client3->createPost($blogName, $data);

    echo $post;

}

?>
```

**Comment by khurshid-alam** [comment]
Same thing happening here.

**Comment by markl181** [comment]
I did a bit of testing on this. It looks like if you create a second instance of the API, then make a new request, you get an authentication error. It's nothing to do with the 'post' method. Most likely this is a restriction on the Tumblr side. 

So for example, this produces the same error for me:

`$client = new Tumblr\API\Client($consumerKey,$consumerSecret,$token,$tokenSecret);
$info = $client->getUserInfo();
echo "<br/><br/>congrats " . $info->user->name . "!"; 
 
$client2 = new Tumblr\API\Client($consumerKey, $consumerSecret, $token, $secret);
$info2 = $client2->getUserInfo();
echo "<br/><br/>more congrats " . $info2->user->name . "!"; `

Whereas this works fine:

`$client = new Tumblr\API\Client($consumerKey,$consumerSecret,$token,$tokenSecret);
$info = $client->getUserInfo();
echo "<br/><br/>congrats " . $info->user->name . "!"; 
 
$info2 = $client->getUserInfo();
echo "<br/><br/>more congrats " . $info2->user->name . "!"; `

If you don't create a second instance, you should be ok.

**Comment by ceyko** [comment]
@andrewbecks It looks like your passing up parameters based on what Link Post _responses_ look like. However, if you check the [Link Post Creation docs](https://www.tumblr.com/docs/en/api/v2#plink-posts), it actually requires a few different parameters.

Try making a request with these parameters:

```
$data = [
    'type' => 'link',
    'url' => 'http://www.yahoo.com',
    'description' => 'my sample tumblr post',
    'thumbnail' => 'https://i.ytimg.com/vi/m5d1FlSeF-M/maxresdefault.jpg',
    'author' => 'me',
]
```

Which will produce a post including these parameters:
```
        "link_image": "https://68.media.tumblr.com/d6ef4c3eb45e1920ea3c91c01870eaac/tumblr_oszjtpmuJC1s4ftbf_og_540.jpg",
        "link_image_dimensions": {
          "width": 540,
          "height": 304
        },
        "link_author": "me",
        "excerpt": null,
        "publisher": "yahoo.com",
        "description": "<p>my sample tumblr post</p>",
```
