### ISSUE TITLE
How to set this up on web hosting without composer

### ISSUE THREAD

**Issue by NekoTony** [tumblr/tumblr.php#74]
title says all

**Comment by ceyko** [comment]
Install composer on your local machine, `composer require tumblr/tumblr`, and then gather all the files and dependencies it created and upload them to your web host. You can repeat this as necessary to update the packages well.

There are some stackoverflow [questions](https://stackoverflow.com/questions/20894518/how-do-i-install-composer-on-a-shared-hosting) that may [help](https://stackoverflow.com/questions/15969948/use-composer-without-ssh-access-to-server) you as well.
