### ISSUE TITLE
Error Class not found

### ISSUE THREAD

**Issue by clozeQH** [tumblr/tumblr.php#76]
Hi i wanna ask about this error
"Php fatal error: class 'Tumblr\API\Client' not found in........."

The  code:

$client= new Tumblr\API\Client ($consumerKey, $consumerSecret);
$client ->setToken ($token, $tokenSecret);

I had read about this error n tried to do like they said but the code still had this error

Someone please help

**Comment by foush** [comment]
Hi, two things:
you'll need to make sure you've installed tumblr [via composer](https://getcomposer.org/doc/00-intro.md) with the command `composer require tumblr/tumblr`

If you've already done that, then you'll also need to make sure you're loading composer in your script somewhere before you try and instantiate `$client = new Tumblr\Api\Client...` this typically looks like:

```
require_once 'vendor/autoload.php'
```

Give that a try and see if you have any luck.

**Comment by clozeQH** [comment]
thank you for ur reply.. this is my code.. i already include the vendor/autoload.php; but it dont work

<?php

passthru('clear');

use Tumblr\API;

include("keys.php");
include("vendor/autoload.php");

$client = new Tumblr\API\Client($consumerKey,$consumerSecret);
$client->setToken($token,$tokenSecret);

$user_info = $client->getUserInfo;
echo $user_info;

**Comment by clozeQH** [comment]
when i run the composer require tumblr/tumblr , the terminal give this :
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tumblr/tumblr No version set (parsed as 1.0.0) is satisfiable by tumblr/tumblr[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by foush** [comment]
> when i run the composer require tumblr/tumblr , the terminal give this :
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - The requested package tumblr/tumblr No version set (parsed as 1.0.0) is satisfiable by tumblr/tumblr[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
> 
> Installation failed, reverting ./composer.json to its original content.

This indicates you do not have the tumblr client library installed because one of your project's dependencies conflicts with one of the dependencies of this client (likely Guzzle)

**Comment by clozeQH** [comment]
should i download again the composer n remove the old one? 
if Guzzle, i already installed 'sudo apt-get install php-guzzle'
sorry i'm new to this..

**Comment by clozeQH** [comment]
im having a little problem here..

im installing ubuntu back after uninstall it..and the i try to run the exact tumblr api code that i have before but it keep repeating the same error..
 "Php fatal error: class 'Tumblr\API\Client' not found in........." 

and, how can i generate composer.json back? because after i install composer, composer.json not auto-generate itself.

**Comment by clozeQH** [comment]
now im using composer.json from tumblr [https://github.com/tumblr/tumblr.php](url)
