### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it.

### ISSUE THREAD

**Issue by emerika** [tumblr/tumblr.php#81]
This dependency is preventing me from using more and more other packages that have been updated. Could you merge the pull request that fixes this and do a release please?

**Comment by westy92** [comment]
This has been merged.  @ceyko, could we please get this released?

**Comment by oligriffiths** [comment]
@westy92 @ceyko is away on vacation. I will look into this tomorrow.

**Comment by ceyko** [comment]
Fixed via #61 and v0.3.0
