### ISSUE TITLE
400 Bad Request Exception for Unlike post

### ISSUE THREAD

**Issue by angstdeprived** [tumblr/tumblr.php#82]
Steps to produce issue:

calling unlike feature as per official php api guide

example:
$client->unlike(1234567890, 'abcd1234');

Then it will throw uncaught Uncaught Tumblr\API\RequestException: [400]: Bad Request.

Really appreciate if I could be enlightened if there's any parameter name change for Unlike request, thanks!

**Comment by oligriffiths** [comment]
@angstdeprived Has the configured user previously liked the post? If not then you will get an error as seen.

**Comment by angstdeprived** [comment]
@oligriffiths yes, the configured user has already liked the post previously

**Comment by angstdeprived** [comment]
I finally found why. I'm trying to unlike a reblog using post ID of my blog. It turns out I can't like/unlike any of my reblogs/original post. It works fine if I like/unlike other blog's original posts. I guess this is a new tumblr policy,

**Comment by oligriffiths** [comment]
Yup, you shouldn't be able to like your own posts. Glad you solved it.

**Comment by angstdeprived** [comment]
Yeah I'll keep note in the future, thanks for the response @oligriffiths ! Also I found that I also can't unlike posts from blogs that has blocked me (I got 403 forbidden response). 

I understand that liking posts from blog that has blocked you must be disabled to prevent it to show on their notifications. But unliking their post should be permittable logically since unliking won't show by default in notifications. Do you have any idea to unlike posts from blogs that has blocked you? Or is it possible to consider to change that policy in the future?

I'm sorry if this is slight OOT but I don't know where else to ask since I've submitted this to Tumblr team since years ago and I don't think it's in the Tumblr developer's to do list since it's not an error issue. Really appreciate it if tumblr team could consider changing that policy in the future. 

Thanks in advance!
