### ISSUE TITLE
unable to create post

### ISSUE THREAD

**Issue by anuj9196** [tumblr/tumblr.php#85]
I'm trying to create a new video post using user's access token and secret.
```
$tumblr = new Client(
      $this->app_key,
      $this->app_secret,
      $this->access_token,
      $this->token_secret
);
$info = $tumblr->getUserInfo();
debug($ino);

$title = 'New Post';
$data = [
        'data' => $video_file
];
$result = $tumblr->createPost($title, $data);
debug($result);
```

`getUserInfo()` is working fine but `createPost` returning exception error
```
Tumblr\API\RequestException: Not Found
```

**Comment by ceyko** [comment]
@anuj9196 I think you may be using mixing up the arguments in your method call. The first parameter in [`createPost()`](https://github.com/tumblr/tumblr.php/blob/v0.3.0/lib/Tumblr/API/Client.php#L224) is `$blogName`. So, the reason you're getting a 404 Not Found error is because the blog `New Post.tumblr.com` does not exist.

Additionally, there are a few required request parameters in the [Post Creation API](https://www.tumblr.com/docs/en/api/v2#posting) that you'll need to include as well.

Try something like this:

```
$blog_name = 'yourblog';
$caption = 'New Post';
$video_file = '/path/to/video';
$data = [
    'type' => 'video',
    'caption' => $caption,
    'data' => $video_file,
];
$result = $tumblr->createPost($blog_name, $data);
```
(Note that Video Posts do not have titles, only captions.)

Or, you can automatically post to your primary blog without giving its name via:

```
$blog_name = $tumblr->getUserInfo()->user->name;
```

**Comment by anuj9196** [comment]
Following your suggestion not is giving error.
```
Tumblr\API\RequestException: Unauthorized
```
Am I missing something? Again `getUserInfo()` is working but video uploading is not.

**Comment by anuj9196** [comment]
So, do you mean I need to first create a blog?

I used `$blog_name = $tumblr->getUserInfo()->user->name;` and now `Unauthorized` error has gone. 

But I am able to post only one video. Posting second video is giving
```
Tumblr\API\RequestException: Bad Request (You may only upload one video per post.)
```

**Comment by ceyko** [comment]
@anuj9196 By creating an account, you already have a blog. You just need to specify which blog you want to post the video to. The code sample I provided (`$blog_name = $tumblr->getUserInfo()->user->name`) will let you post to your [primary blog](https://tumblr.zendesk.com/hc/en-us/articles/226340048-Primary-vs-secondary-blogs). If you want to post to one of your secondary blogs, you can include it's name instead.

For example, If I were posting to `staff.tumblr.com`, I would do the following:
```
$tumblr->createPost('staff', $data);
```

---

Including multiple uploaded videos in a single post is not supported on Tumblr. You'll need to make a separate post for every video you want to include.

Also note that if you mistakenly specify `data` as an array, e.g., `'data' => [ $video_file ]`, you will also get the same "Only one video per post" error.

**Comment by anuj9196** [comment]
Can you give me a sample code of posting video file and create a new post.

This is what I'm doing
```
$blog_name = $tumblr->getUserInfo()->user->name;
$caption = $title;
$data = [
      'type' => 'video',
      'caption' => $caption,
      'data' => $video_file,
];

$result = $tumblr->createPost($blog_name, $data);
```
and this is giving error 
```
Only one video per post
```
As far as I have understand, `createPost` function will create a new post. If not, then please guide how to create a new post

**Comment by anuj9196** [comment]
Can you give me a sample code of posting video file and create a new post.

This is what I'm doing
```
$blog_name = $tumblr->getUserInfo()->user->name;
$caption = $title;
$data = [
      'type' => 'video',
      'caption' => $caption,
      'data' => $video_file,
];

$result = $tumblr->createPost($blog_name, $data);
```
and this is giving error 
```
Only one video per post
```
As far as I have understand, `createPost` function will create a new post. If not, then please guide how to create a new post
