### ISSUE TITLE
getBlogAvatar retrurns null 

### ISSUE THREAD

**Issue by Fatih90** [tumblr/tumblr.php#87]
suddenly i keep getting empty results when trying to get any blog avatar using this code

```php
$client = new Tumblr\API\Client('FaXbG***', 'qxuPr***');
$client->getBlogAvatar('david', 96);
```

https://api.tumblr.com/v2/blog/david.tumblr.com/avatar/96

not sure why its not getting the image, it worked before 🤒

**Comment by jasonpenny** [comment]
This should be fixed now, thanks for reporting it!
